Cep api
MateusQ7/opa-web-frontend pull request #9
Opened 2023-09-25 18:46 UTC by EduardoLott

Adicionei o serviço "cep" para validar o cep no registro do usuário

2023-09-25 21:31 UTC, PCDuarte25 requested changes

2023-09-25 21:31 UTC, PCDuarte25 commented on src/app/cep/cep.service.ts
> +  buscarCep(cep: string): Observable<any> {
```suggestion
  searchForCep(cep: string): Observable<any> {
```

2023-09-25 21:31 UTC, PCDuarte25 commented on src/app/cep/cep.service.ts
> +    const apiUrl = `https://viacep.com.br/ws/${cep}/json/`;
transforma isso numa constante fora do método porque fica mais fácil atualizar no futuro caso precise; Formatar objeto(cauê)

2023-09-25 21:31 UTC, PCDuarte25 commented on src/app/user-register/user-register.component.html
> +                        <input type="text" [(ngModel)]="cep" (input)="buscarCep()" formControlName="cep" class="box-info" placeholder="Insira o cep" font-family="Poppins"/>
```suggestion
                        <input type="text" [(ngModel)]="cep" (input)="searchForCep()" formControlName="cep" class="box-info" placeholder="Insira o cep" font-family="Poppins"/>
```

2023-09-25 21:31 UTC, PCDuarte25 commented on src/app/user-register/user-register.component.ts
> +  estado: string = '';
```suggestion
  cep: string = '';
  neighborhood: string = '';
  city: string = '';
  state: string = '';
```

2023-09-25 21:31 UTC, PCDuarte25 commented on src/app/user-register/user-register.component.ts
> +    const cep = this.cep.replace(/\D/g, '');
Bota a regex numa constante também

2023-09-25 21:31 UTC, PCDuarte25 commented on src/app/user-register/user-register.component.ts
> +  buscarCep() {
```suggestion
  searchForCep() {
```

2023-09-25 21:31 UTC, PCDuarte25 commented on src/app/user-register/user-register.component.ts
> +      this.cepService.buscarCep(cep).subscribe(
```suggestion
      this.cepService.searchForCep(cep).subscribe(
```

2023-09-25 21:31 UTC, PCDuarte25 commented on src/app/user-register/user-register.component.ts
> +    if (cep.length === 8) {
Coloca esse 8 numa constante também

2023-09-25 21:31 UTC, PCDuarte25 commented on src/app/user-register/user-register.component.ts
> +          console.log('Dados do CEP:', data);
```suggestion
```
Esqueceu de tirar o `console.log`

2023-09-25 21:31 UTC, PCDuarte25 commented on src/app/user-register/user-register.component.ts
> +          this.estado = data.uf;
```suggestion
          this.neighborhood= data.logradouro;
          this.city = data.localidade;
          this.state = data.uf;
```

2023-09-25 21:31 UTC, PCDuarte25 commented on src/app/user-register/user-register.component.ts
> +          // Trate os erros, por exemplo, exiba uma mensagem de erro ao usuário
Pode deixar esse erro ai no console, mas tem que ter uma validação pro usuário saber o que aconteceu.

2023-09-26 01:25 UTC, EduardoLott commented on src/app/user-register/user-register.component.ts
> +  estado: string = '';
Cuidado que logradouro é rua, neighborhood é bairro

2023-09-26 16:43 UTC, PCDuarte25 requested changes

2023-09-26 16:43 UTC, PCDuarte25 commented on src/app/cep/cep.service.ts
> +          uf: data.uf,
@EduardoLott continua em portugues...

2023-09-26 16:43 UTC, PCDuarte25 commented on src/app/cep/cepData.interface.ts
> +    uf: string;
@EduardoLott continua em portugues...

2023-09-26 16:43 UTC, PCDuarte25 commented on src/app/user-register/user-register.component.ts
> +    const cep = this.cep.replace(/\D/g, '');
Continua sem ta numa constante

2023-09-26 16:43 UTC, PCDuarte25 commented on src/app/user-register/user-register.component.ts
> +    if (cep.length === 8) {
Continua sem ta numa constante

2023-09-26 16:43 UTC, PCDuarte25 commented on src/app/user-register/user-register.component.ts
> +            console.log('Dados do CEP:', data);
tem que remover esse console.log

2023-09-26 16:48 UTC, PCDuarte25 commented
Outra coisa @EduardoLott tira os comentários em português ou traduz eles pra inglês, não pode ter nada em português em código apenas string que vai aparecer pra o usuário final tem que ta em português.

2023-09-26 17:21 UTC, PCDuarte25 approved these changes

2023-09-26 18:27 UTC, merged